# Generated by Django 2.1 on 2018-08-31 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudid', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 8, 31, 10, 16, 11, 39062, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Datanode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataunitid', models.CharField(max_length=200)),
                ('cloudid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ges.Cloud')),
            ],
        ),
    ]
